### ISSUE TITLE
Snapshot API support

### ISSUE THREAD

**Issue by IvannKurchenko** [rickfast/consul-client#314]
Hello!

Thank you very much for all your hard work - this client looks really great, but I did not find [Snapshot API](https://www.consul.io/api/snapshot.html) implementation. Excuse me, if it's duplicate or invalid.

Thanks!

**Comment by yfouquet** [comment]
Hi @IvannKurchenko,

I have checked with okhttp and the only way to use `InputStream ` would be to use `BufferedInputStream`.
This implementation has the drawback of loading all the data in memory (at some point).
Hence, if the snapshot is saved in a file, it is better to use a file directly (with `FileInputStream`).
I can still add support for byte array if you are interested, otherwise i think the issue can be closed.

**Comment by IvannKurchenko** [comment]
Hello, @yfouquet !

That's fine, I'm happy with current implementation.
Thank you very much for your work, well done!

Regards,
Ivan!
